apiVersion: apps/v1
kind: Deployment
metadata:
  name: attic-music
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attic-music
  template:
    metadata:
      labels:
        app: attic-music
    spec:
      initContainers:
        - name: config-gen
          image: busybox
          env:
            - name: LASTFM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: lastfm-secret
                  key: LASTFM_API_KEY
          command:
            - sh
            - -c
            - |
              cat > /config/config.json <<EOF
              {
                "server": "https://gonic.ekskog.net",
                "username": "admin",
                "lastfmUser": "your-lastfm-username",
                "lastfmKey": "$LASTFM_API_KEY"
              }
              EOF
          volumeMounts:
            - name: config-vol
              mountPath: /config
      containers:
        - name: attic
          image: ghcr.io/ekskog/attic-music:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-vol
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-vol
          emptyDir: {}