apiVersion: apps/v1
kind: Deployment
metadata:
  name: attic-music
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attic-music
  template:
    metadata:
      labels:
        app: attic-music
    spec:
      containers:
        - name: attic
          image:  ghcr.io/ekskog/attic-music:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: lastfm-secret
