apiVersion: v1
kind: Secret
metadata:
  name: lastfm-secret
  namespace: webapps
type: Opaque
stringData:
  LASTFM_API_KEY: "ce0566fc723a503e86bcf368a65fd719"
  LASTFM_API_SECRET: "9fd08a0911c5f0813e762e5bf40060c6"
